nodeLinker: node-modules

logFilters:
    -   code: YN0007
        level: discard
    -   code: YN0008
        level: discard
    -   code: YN0013
        level: discard

yarnPath: .yarn/releases/yarn-4.0.1.cjs

enableGlobalCache: true
enableTelemetry: false
