FROM node:14-buster-slim AS backend-build
WORKDIR /build
COPY . .
RUN yarn workspaces focus andeo-lunch-backend

FROM node:14-buster-slim
RUN mkdir -p /srv/andeo-lunch/backend
WORKDIR /srv/andeo-lunch/backend
COPY --from=backend-build /build/node_modules /srv/andeo-lunch/node_modules
COPY --from=backend-build /build/backend      /srv/andeo-lunch/backend
RUN mv config-docker.json config.json
EXPOSE 3000
CMD ["yarn", "serve"]
