version: '3.6'

# This is an example deployment which will need to be adapted to your needs!

# You may remove the db container and use an existing database server.

# To create users:
# docker exec -ti andeo-lunch-backend yarn db:createUser

services:
    db:
        image: mariadb:10.6
        container_name: andeo-lunch-db
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db-root-password
            MARIADB_ROOT_HOST: localhost
            MARIADB_DATABASE: andeolunch
            MARIADB_USER: andeolunch
            MARIADB_PASSWORD_FILE: /run/secrets/db-user-password
        secrets:
            - db-root-password
            - db-user-password
        volumes:
            - ./data:/var/lib/mysql
            - ./andeolunch.cnf:/etc/mysql/mariadb.conf.d/andeolunch.cnf

    backend:
        image: andeo-lunch-backend
        container_name: andeo-lunch-backend
        restart: unless-stopped
        environment:
            MARIADB_HOST: db
            MARIADB_DATABASE: andeolunch
            MARIADB_USER: andeolunch
            MARIADB_PASSWORD_FILE: /run/secrets/db-user-password
        secrets:
            - db-user-password
        ports:
            - 3000:3000
        depends_on:
            - db

    app:
        image: andeo-lunch-app
        container_name: andeo-lunch-app
        restart: unless-stopped
        ports:
            - 8080:80
        depends_on:
            - backend

secrets:
    db-root-password:
        file: ./db-root-password.secret
    db-user-password:
        file: ./db-user-password.secret
